AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Lambda TypeScript with API Gateway for blue/green deployments

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs20.x

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  HelloFunctionName:
    Description: Hello World Lambda Function Name
    Value: !Ref HelloFunction
  HelloFunctionArn:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloFunction.Arn
